spring:
  application:
    name: PCL MICRO SERVICES

server:
  port: 2222


eureka:
  client:
    service-url:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://localhost:8761}/eureka/
